### ISSUE TITLE
新建连接时出现插件未加载错误

### ISSUE THREAD

**Issue by jiqing112** [dbkangaroo/kangaroo#12]
![6b622b8b83a04160.png](https://i.loli.net/2019/10/14/DaIsGehMTwQFlXb.png)

**Comment by jiqing112** [comment]
点击connect没反应，test connect显示成功，save connect点了提示保存成功，主界面没反应，关掉新建连接的窗口之后主界面一下多出来好多连接信息
![-711a70e1244dc883.png](https://i.loli.net/2019/10/14/4iuBYwMKQm2hRSy.png)

**Comment by taozuhong** [comment]
__分析__
MySQL 客户端库缺失导致无法连接

__解决方案__

带上MySQL 客户端库即可

**Comment by taozuhong** [comment]
临时解救办法：切换密码验证方式
```bash
1.) Open terminal / hyper
2.) mysql -u root -p
3.) Enter your password
4.) ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY 'password';
```
