### ISSUE TITLE
[Bug]: 密码包含特殊字符@，链接报错

### ISSUE THREAD

**Issue by Phyday** [dbkangaroo/kangaroo#121]
### Same issue exist?

- [x] I have searched the issues (https://github.com/dbkangaroo/kangaroo/issues)

### Version of Kangaroo

6.1.1

### Branch of Kangaroo

Multiple

### Platform of Kangaroo

Windows (x86-64)

### Database system with name and version

Postgresql，

### Bug detail

用户名和密码没错的，用dbeaver正常连接
![image](https://github.com/user-attachments/assets/dae68253-86eb-48f8-8fb3-9a323147833a)

![image](https://github.com/user-attachments/assets/3d8998d4-0568-41fa-92ae-72d0619be5aa)

**Comment by taozuhong** [comment]
感谢反馈，已对连接字符串做了升级，下一个版本（6.2）即可修复。
