### ISSUE TITLE
Postgres tables not visible

### ISSUE THREAD

**Issue by gauravmanchanda** [dbkangaroo/kangaroo#46]
Able to connect to the DB just fine. But when I select a DB, then schema, then click on tables, I don't see any, the list comes out blank.

When I try to export the DB, it says there are no tables

Kangaroo Version,: 0.23
Platform: Manjaro 20
WM: XFCE
Postgresql 12.2

![TablesMissing](https://user-images.githubusercontent.com/1324643/82741704-b2cf8b00-9d72-11ea-91bd-9e4d97744a30.jpg)

Sqlite works perfectly though

**Comment by taozuhong** [comment]
@gauravmanchanda PostgreSQL version?

**Comment by gauravmanchanda** [comment]
Missed out the major detail, sorry. Its Postgres 12.2

**Comment by taozuhong** [comment]
Analyze:
PostgreSQL 11 :
`SELECT table_name, table_schema FROM information_schema.tables WHERE table_type = 'BASE TABLE' AND table_catalog = 'postgres' AND table_schema = 'public'  ORDER BY table_name ASC;`

PostgreSQL 12: 
`SELECT table_name, table_schema FROM information_schema.tables WHERE table_type = 'BASE TABLE' AND table_catalog = 'postgres' AND table_schema in ['pg_catalog', 'information_schema']  ORDER BY table_name ASC;`

**Comment by taozuhong** [comment]
done, ship with the next version.

**Comment by gauravmanchanda** [comment]
Awesome. Thanks 👌🏻

**Comment by taozuhong** [comment]
the new version has shipped, pls try to verify the solution. 

thanks for your feedback.
