### ISSUE TITLE
能否出一个解压即用的版本?

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [dbkangaroo/kangaroo#58]
如题,能否出一个解压即用的版本? 感谢

**Comment by taozuhong** [comment]
Windows 平台已经有解压即可用的版本，Linux 平台版本需要自己安装依赖库，测试可用，就是 MacOS上目前还没整好，测试未通过；
[Linux 平台安装指导手册](https://dbkangaroo.github.io/zh/document/install_linux.html)

**Comment by taozuhong** [comment]
@ziyouchutuwenwu 你期望是哪个平台解压即可用？

**Comment by ziyouchutuwenwu** [comment]
> @ziyouchutuwenwu 你期望是哪个平台解压即可用？

您好,希望是linux, amd 64

**Comment by taozuhong** [comment]
好，那我额外添加一个脚本，通过脚本完成依赖库的安装。
