### ISSUE TITLE
Make kangaroo portable

### ISSUE THREAD

**Issue by lisxray** [dbkangaroo/kangaroo#59]
Currently, the configuration directory defaults to `~/.kangaroo`.

It would be nice if kangaroo is portable.

For example, when  a folder named `profile` exists in the program directory, kangaroo writes all its config to the folder automatically.

**Comment by taozuhong** [comment]
@lisxray you mean store all configuration data in the program directory?

**Comment by lisxray** [comment]
Yes.

It allows running on a USB stick and easy transfer of the program with data.

**Comment by taozuhong** [comment]
Got it, I'll support it at next version

**Comment by taozuhong** [comment]
Solved it, pls see it in the next version

**Comment by lisxray** [comment]
> Solved it, pls see it in the next version

Thank you.

Could you document it [here](https://dbkangaroo.github.io/document/install_windows.html#install-kangaroo)?

**Comment by taozuhong** [comment]
Great idea, done as you suggested:  [here](https://dbkangaroo.github.io/document/install_windows.html#install-kangaroo)
