### ISSUE TITLE
新建链接的时候，如果没有填写数据库名称。那么打开后几处功能出现 no database selected

### ISSUE THREAD

**Issue by chinaapus** [dbkangaroo/kangaroo#61]
新建链接的时候，如果没有填写数据库名称。那么打开后几处功能出现 no database selected ，如右键复制表结构 等功能

**Comment by chinaapus** [comment]
这个也不算是个BUG ，但是不填数据库名称有时候也是很需要。比如打开 本地数据库，需要浏览全部库 。否则一个库一个链接，那就有点麻烦了。

**Comment by taozuhong** [comment]
@chinaapus 原因找到了，是因为连接时数据库名字为空导致的，改进方法是：数据库名字为空时默认设置为 mysql
