### ISSUE TITLE
提示MySQL server has done away后,没有自动\手动重连

### ISSUE THREAD

**Issue by Colourfulzi** [dbkangaroo/kangaroo#63]
版本:0.99.1.200824 Win10 AMD64

问题:连接某个数据库后过一段时间进行任意SQL查询操作提示"MySQL server has done away"，但未进行重连操作，也没找到任何手动重连操作。
如果此时进行”刷新目录树“操作，会导致左侧变为空白。

**Comment by taozuhong** [comment]
谢谢反馈， 这是MySQL自动中断长时间未使用的连接，需要家保持连接的参数。

**Comment by taozuhong** [comment]
MySQL / MariaDB 默认超时时间是28800即8个小时，86400为24个小时:

设置超时时间，临时生效（以秒为单位）： 
```sql
msyql> set global wait_timeout=86400;
msyql> set global interactive_timeout=86400;
```

修改配置文件 /etc/my.cnf.d/server.conf
```ini
[mysqld]
wait_timeout=86400
```

**Comment by taozuhong** [comment]
重新做了连接超时设置支持，看看效果先；
