### ISSUE TITLE
plugin caching sha2 password could not be loaded

### ISSUE THREAD

**Issue by XiaopoSu** [dbkangaroo/kangaroo#64]
![image](https://user-images.githubusercontent.com/9793938/91658110-ef8cea00-eaf8-11ea-93e5-be3009bbb8ef.png)

环境：windows 10 家庭版 64位
mysql 5.7

**Comment by taozuhong** [comment]
谢谢反馈，库已经带了，是路径搜寻有问题；

**Comment by taozuhong** [comment]
找到解决办法了，只要设置环境变量就可以加载：
环境变量 | 变量说明
-- | --
LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN | Enable mysql_clear_password authentication plugin;
LIBMYSQL_PLUGIN_DIR | Directory in which to look for client plugins.
LIBMYSQL_PLUGINS | Client plugins to preload.

[参考链接: MySQL 环境变量](https://dev.mysql.com/doc/refman/5.7/en/environment-variables.html)

**Comment by taozuhong** [comment]
在安装脚本中已添加环境变量 LIBMYSQL_PLUGIN_DIR。
