### ISSUE TITLE
No provider postgresql installed

### ISSUE THREAD

**Issue by poluha** [dbkangaroo/kangaroo#70]
Try connect to postgresql on mac and... what does it means "no provider postgresql installed"
Postgresql inside docker container

**Comment by taozuhong** [comment]
Thanks for your feedback, 

the brew libgda package not yet contain all providers, so it missing in the installer package:
https://formulae.brew.sh/formula/libgda

I'll try other ways to improve this issue.

**Comment by taozuhong** [comment]
Solved in 1.9.1
