### ISSUE TITLE
No provider 'MySQL' installed

### ISSUE THREAD

**Issue by nopol** [dbkangaroo/kangaroo#77]
I use kangaroo-1.5.1.201231-macos.dmg

Connect Mysql error,message is "No provider 'MySQL' installed"

**Comment by taozuhong** [comment]
Step in progress: 
![image](https://user-images.githubusercontent.com/13451009/118954792-b18a6b80-b990-11eb-9173-9b10f7b343cd.png)

**Comment by taozuhong** [comment]
Solved in 1.9.1
