### ISSUE TITLE
未填写的时候可以直接用ip+端口直接做连接名

### ISSUE THREAD

**Issue by Tsingkai** [dbkangaroo/kangaroo#83]
![image](https://user-images.githubusercontent.com/45168225/121620604-34d54380-ca9d-11eb-83f5-e857623b7655.png)
未填写的时候可以直接用ip+端口直接做连接名 ，如```127.0.0.1:3306```想名字，费脑子

**Comment by taozuhong** [comment]
命名模式为： Untitled@PostgreSQL(127.0.0.1:5432)
