### ISSUE TITLE
希望增加支持jdbc驱动的解析，满足基本的sql查询

### ISSUE THREAD

**Issue by imic07** [dbkangaroo/kangaroo#86]
类似idea的数据库管理, 配置jdbc驱动包，然后就可以连接数据库进行查询了.

这样很多国产数据库也能用了.

**Comment by taozuhong** [comment]
尝试支持，奈何对 JAVA 工具链这一块不太熟，需要大家的支持：
https://gitlab.gnome.org/GNOME/libgda/-/merge_requests/180

**Comment by taozuhong** [comment]
新版本中将会支持。

**Comment by taozuhong** [comment]
已经通过 ODBC 提供数据库通用支持，请留意 1.99.1以后的版本哈
