### ISSUE TITLE
Kangaroo袋鼠数据库工具 v1.94.1 (Dev)已知缺陷报告

### ISSUE THREAD

**Issue by TotheAnts** [dbkangaroo/kangaroo#95]
1.初始界面点击【新建连接】无反应，需双击其他空白位置
2.【主菜单】>>【视图】中有异常字符“丄”
3.点击【主菜单】下【更新】、【报告缺陷】无反应

**Comment by taozuhong** [comment]
感谢您对袋鼠的关注和认可。

针对问题答复如下：
1. 【新建连接】无反应 属于 GTK bug，它双击是可以打开的，因为精度原因，所以双击行为不靠谱。
2. 异常字符“丄” 属于 Pango 字体渲染问题，或许升级库可以解决。
3. 可以重现问题，但是开发环境可以打开链接，可能属于配置文件未搭载。

**Comment by taozuhong** [comment]
已解决。
