### ISSUE TITLE
运行时报错：kangaroo: symbol lookup error: /usr/lib/libkangaroo.so: undefined symbol

### ISSUE THREAD

**Issue by deamonet** [dbkangaroo/kangaroo#98]
**Enviroment:**
 - Kangaroo Version: 1.97 Dev
 - OS: Manjaro Linux x86_64 
 - Kernel: 5.15.60-1-MANJARO
 - Desktop Environment: Xfce 4.16

**Describe the bug**
运行时报错（Portable版本也是这样）：
kangaroo: symbol lookup error: /usr/lib/libkangaroo.so: undefined symbol: adw_message_dialog_new, version LIBADWAITA_1_0

**Comment by taozuhong** [comment]
亲，需要安装 libadwaita 新版本：1.2 以上版本
